import type { SopRule } from "./types";

export const SOP_RULES: SopRule[] = [
  {
    id: "general_dental",
    category: "General",
    applies_to: ["bariatric", "joint", "general"],
    finding: "Dental visit > 6 months ago OR pending dental work",
    fact_fields: ["dental_visit_within_6_months", "has_pending_dental_work"],
    status: "Action Required",
    action: "Instruct patient to complete dental clearance before Consultation.",
    severity: "warning",
  },
  {
    id: "joint_smoking",
    category: "Joint",
    applies_to: ["joint"],
    finding: "Active smoker or quit within last 3 months",
    fact_fields: ["smoking_status"],
    status: "Deferred",
    action:
      "Refer to Smoking Cessation education/support; pause case for 3 months.",
    severity: "critical",
  },
  {
    id: "joint_no_pt",
    category: "Joint",
    applies_to: ["joint"],
    finding: "No attempt at physical therapy or structured exercise",
    fact_fields: ["has_attempted_pt_or_exercise"],
    status: "Ineligible",
    action: "Refer to 6–12 week conservative physical therapy trial.",
    severity: "critical",
  },
  {
    id: "joint_hba1c",
    category: "Joint",
    applies_to: ["joint"],
    finding: "HbA1c > 7.0",
    fact_fields: ["hba1c_value"],
    status: "Review",
    action: "Flag for Clinical MD Review for glucose optimization.",
    severity: "warning",
  },
  {
    id: "joint_opioid",
    category: "Joint",
    applies_to: ["joint"],
    finding: "Daily opioid use for more than 3 months",
    fact_fields: ["daily_opioid_use_over_3_months"],
    status: "High Complexity",
    action: 'Flag for Anesthesia "High Risk" Consult.',
    severity: "high",
  },
  {
    id: "bariatric_revision",
    category: "Bariatric",
    applies_to: ["bariatric"],
    finding: "History of prior weight-loss surgery",
    fact_fields: ["has_prior_weight_loss_surgery"],
    status: "Revision",
    action: "Flag as Revision Case; requires specialized surgical review.",
    severity: "info",
  },
  {
    id: "bariatric_no_egd",
    category: "Bariatric",
    applies_to: ["bariatric"],
    finding: "No endoscopy (EGD) in the last 3 months",
    fact_fields: ["has_recent_endoscopy"],
    status: "Action Required",
    action: "Instruct patient to schedule EGD after Consultation.",
    severity: "warning",
  },
  {
    id: "bariatric_no_rd",
    category: "Bariatric",
    applies_to: ["bariatric"],
    finding: "No Registered Dietician identified",
    fact_fields: ["has_registered_dietician"],
    status: "Hold",
    action:
      "Provide in-network RD list; patient must confirm RD before referral.",
    severity: "warning",
  },
];
